  
language: groovy
before_install:
  - wget https://services.gradle.org/distributions/gradle-7.1-bin.zip
  - unzip -qq gradle-7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-7.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
- gradle -v
install:
- - gradle distPlugin
jdk:
- oraclejdk9
script:
- ls build
deploy:
  provider: releases
  api_key:
    secure: D1Bp9ebMQgNIRB8ALGSs7A
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Amiya-873/Send-SMTP-Email-UCD
    
