  
language: groovy
before_install:
  - wget https://services.gradle.org/distributions/gradle-7.1-bin.zip
  - unzip -qq gradle-7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-7.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
- gradle -v
install:
- - gradle distPlugin
jdk:
- oraclejdk11
script:
- ls build
deploy:
  provider: releases
  api_key: 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
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: UrbanCode/Send-SMTP-Email-UCD
    
