  
language: groovy
before_install:
  - wget https://services.gradle.org/distributions/gradle-7.1-bin.zip
  - unzip -qq gradle-7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-7.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
- gradle -v
install:
- - gradle distPlugin
jdk:
- oraclejdk9
script:
- ls build
deploy:
  provider: releases
  api_key:
    secure: L85Tm1ZdfImlY0D6MtYAnFiOyt/w//iFz7Y/tpvaNZgcynIsD7Ik4io+jDhIa6NraWjp9KS1NhLVK4IuDBCyaxO7AYVv6HAKTPIrSJiVN+TW4iHvw9NTBsAiqCv1OKxfh3Znh5BziQ2luV/ybFvY9YaHq7Z89B9bbfvGw3H/xfMVqadj+r4iAYx2VSEgn+FbSbgU1ESzgVEzFiu45vEs/cObAyKOUh7zuniPgbgE/QcDlysudyH7tWF/RYY1S+kLg8onWz4sRiJOXwdEhlmzHdOZAgLufvwsxRRtOgY8oCMYebPK6APfuiTkFfaPBwodzcjTCqP4SxZu+lusuRIhpYYr9nSfO6y769EK9ZL+EfeSTZjxreZ1oY0n7uqRJTLx1mzsBVVszpnhMDP6XybbQobP4ZKtNYt5b0hkyTs0R3jTeWg6cjpj0WMsLiHaa0HjDazKftL4HYeCc81CnfmwPdGW4/BSDL07Drl2yzUfCzBX0xKGF0GFpimhCmZpida4YukhLSoehvNL0nd2Hnb4LUQK6Fp3tuBbxiupQhWqtQC1iesSZrPZPixXaXT16QTvmG5FaIMwP8BWpB8hBD84bKFa/aXW49yvzrz1d3RGkgQoGpUAAYxJjzdAh2WMViuyzcDQDE9dEBlojVqaN4NhQt/79MR34uHGN2CGMAYKxdg=
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Amiya-873/Send-SMTP-Email-UCD
    
