  
language: groovy
before_install:
  - wget https://services.gradle.org/distributions/gradle-7.1-bin.zip
  - unzip -qq gradle-7.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-7.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
- gradle -v
install:
- - gradle distPlugin
jdk:
- oraclejdk11
script:
- ls build
deploy:
  provider: releases
  api_key:
    secure: aNfQbwCEV4A1jcqEl/9RAUDS8yEeXTd57mYokudWuqRG40ZChO3X1MkP4TnbE/ry8cFDtPPpnPgnwVrmHCxrODHMzmg1mSBpM1LNNDwSM+L2oqfxbkTM1+vF9OgFJ9OXDQffIK3AiB9zvoLrzggu17ZZPV1RBvH94pgRhjw6sGkcr2bcahtBCmG2obS1RS/vKt3DEikbRpeJK6XzC8JKpaY0ZuzBtvIaKiSccN6vJYjJA/yFEmFXIK+3ZUZBL3Lty9/GAGs28bOrySLo/eZlSAwSYkAXij5BOoGn97PdejAsoteJLLCII2QrAWL2N5gXX2q2tJsAiDG49q6L7gjh1G7Lyb1MFWSFxfQyRwI8UUTlNB3DhKZxeF7K5jOhtoIiQH9XlSR1ATA1eU6aP7LU4oRFjXC1gto72j5jQPZoD6ZqgzmsoXjpjqfti8g9uPgQyoftbplOPc+U1fK5vveKDcGb5sm5Ny5M4tVLu8XM1ZSmF7I0EMrE6/+LavjKYuj0azeAklruUUMUVOwdeIjjukTejJp0thwqb6Kzjp4U0ktc7wLskBPvu6XMQVJJ2xPJDW9TZ0Vz2ZBTomLaRKABM5PjEEHPhUXd2jF5aqUYtyMMHDJ9z0ILxJHpa1wbSrVb0q1meFO7k0T77UvlIPUPEsL05Hq2Q8pr0M9l0prkTDs=
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true

  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: UrbanCode/Send-SMTP-Email-UCD
    
